services:
  - type: web
    name: ai-place-explorer
    runtime: python312
    buildCommand: pip install -r requirements.txt
    startCommand: python api.py
    envVars:
      - key: AIzaSyC7l4q182UQFEEABq7sB9baoZPLQv9-o-Q
        scope: build,runtime
        sync: false
      - key: PORT
        value: "8000"